Update pipeline with K-neighbours-augmentation & Add classification with PyTorch NN
ml-in-programming/bugs-classification pull request #16
Opened 2020-04-07 12:15 UTC by SmirnovOleg

Re-opened

2020-05-09 08:59 UTC, ArtyomLobanov requested changes

2020-05-09 08:59 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetCreator.java
> +        });
Можнно использовать Stream API по максимуму и написать так:
```
var preprocessedNeighbours = solutions.parallelStream()
    .collect(Collectors.toMap(Solution::getSolutionId, generator::process));
var maxTokens = preprocessedNeighbours.values().parallelStream()
    .flatMap(Collection::stream)
    .map(Changes::getChanges)
    .mapToInt(List::size)
    .max();
```
Тогда точно не нужно будет париться со сложностями параллельного программирования - всё уже продумано за нас.

2020-05-09 08:59 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetCreator.java
> +                            || marks.size() == 1 && marks.get(0).equals("")) {
А откуда у нас такие странные метки приходят?

2020-05-09 08:59 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/MarkedClustersSavingUtils.java
> +                if ((float) (maxCounter) / (float) (totalAmount) > 0.6)
Почему вдруг float? Стандартный тип для чисел с плавающей точкой в Java - double. И литерал, с которым вы сравниваете значение `0.6` на самом деле тоже double. Да и отдельно в скобки maxCounter брать не нужно.
`(double) maxCounter / totalAmount > 0.6` или вообще `maxCounter > 0.6 * totalAmaount`

2020-05-11 05:56 UTC, SmirnovOleg commented on src/main/java/org/ml_methods_group/evaluation/preparation/TokenBasedDatasetCreator.java
> +                            || marks.size() == 1 && marks.get(0).equals("")) {
Если кластеру не хватило уверенности (которая 0.6) в метке, всем решениям из него ставится "". Я переписал эту строчку более аккуратно

2020-05-11 10:52 UTC, ArtyomLobanov approved these changes

2020-05-11 10:53 UTC, merged