Add cluster centers heuristic & evaluation on full dataset
ml-in-programming/bugs-classification pull request #17
Opened 2020-05-11 17:10 UTC by SmirnovOleg

2020-05-13 09:23 UTC, ArtyomLobanov requested changes

2020-05-13 09:23 UTC, ArtyomLobanov commented on clustering/src/main/java/org/ml_methods_group/clustering/clusterers/ClusterSizeLimitedHAC.java
> +        super.init(values);
Явно super прописывать не нужно, кроме ситуации, когда ты переопределил метод в наследнике, но сейчас хочешь вызвать реализацию из родителя.

2020-05-13 09:23 UTC, ArtyomLobanov commented on clustering/src/main/java/org/ml_methods_group/clustering/clusterers/ClusterSizeLimitedHAC.java
> +        while (!heap.isEmpty()) {
Я правильно понимаю, что ты переписал этот метод ради изменения этой строчки? 
```java
    @Override
    public Clusters<T> buildClusters(List<T> values) {
        init(values);
        while (!heap.isEmpty() && communities.size() > minClustersCount) {
            final Triple minTriple = heap.first();
            invalidateTriple(minTriple);
            final Community first = minTriple.first;
            final Community second = minTriple.second;
            mergeCommunities(first, second);
        }
        final List<Cluster<T>> clusters = communities.stream()
                .map(c -> c.entities)
                .map(Cluster::new)
                .collect(Collectors.toList());
        return new Clusters<>(clusters);
    }
```
Почему было просто не приравнять в конструкторе minClusterSize к нулю? Кажется, что мы добились бы ровно такого же эффекта.
```java
    public ClusterSizeLimitedHAC(double distanceLimit, int maxClusterSize, DistanceFunction<T> metric) {
        super(distanceLimit, 0 /*  minClusterSize */, metric);
        this.maxClusterSize = maxClusterSize;
    }
```

2020-05-13 09:23 UTC, ArtyomLobanov commented on clustering/src/main/java/org/ml_methods_group/clustering/clusterers/HAC.java
> +    protected final Set<Community> communities = new HashSet<>();
Зависимость по переменным - это всегда нехорошо. В этом плане круто в Kotlin сделано: там за тебя вместо полей делают properties, с которыми визуально можно работать как с переменными, но при этом на самом деле там везде неявно используются getter-ы и setter-ы, а потому можно, например, их (properties) переопределять в наследниках или, например, удалить "поле", но написать свои getter-ы и setter-ы и внешне поведение класса вообще не поменяется. 
Кроме того, модификатор protected в java - штука странная. Он не только открывает доступ наследникам, но и классам в том же пакете.
Что можно сделать: 
1. можно сделать protected getter-ы для интересующих тебя полей
2. можно, как я писал выше, не переписывать метод buildClusters и тогда и поля эти не потребуются
3. ИМХО идеальный вариант - переписать всё через паттерн Состояние. Ввести новый вложенный класс HAC.State, в который перенести все поля класса HAC, кроме метапараметров (distanceLimit, minClustersCount, metric). В методе buildClusters создавать экземпляр этого класса и дальше везде его передавать. Это решит и ещё одну проблему - сейчас в классе есть поля, значение которых зависит от того, считаем ли мы сейчас какие-то кластеры. Из-за этого нельзя. например, использовать экземпляр Clusterer параллельно для нескольких наборов данных. Но тут, конечно, тебе досталась по наследству моя ошибка проектирования.

2020-05-13 09:23 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/Hashers.java
> +    public static String getTokensSeparator() { return TOKENS_SEPARATOR; }
Для static final констант getter обычно и не нужен. Можно их просто public сделать.

2020-05-13 09:23 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/extractors/ManyProblemsBasedChangesExtractor.java
> +        return oracle.process(value);
Потенциальная NullPointerException

2020-05-13 09:23 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/extractors/SparseBOWExtractor.java
> +        private final Map<Integer, Integer> counterByIndex;
Если нет проблем с памятью/временем работы то ок, но эффективнее было сделать два массива/списка: один хранит индексы в возрастающем порядке, в второй значения для этих индексов. Пересекать два отсортированных массива индексов можно очень быстро за O(n) с действительно маленькой константой, в отличие от HashSet-ов, которые довольно тяжеловесны на самом деле. Да и памяти это минимум использует.

2020-05-13 09:23 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/representatives/CentroidPicker.java
> +        V center = values.getElements().get(0);
Потенциальная OutOfBoundsException. Раз уж мы возвращаем список (довольно гибкая структура), то можно для пустого кластера возвращать пустой список.

2020-05-13 09:23 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/representatives/CentroidPicker.java
> +        return List.of(center);
Есть ещё [Collections.singeltonList(x)](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#singletonList-T-) - немного более эффективная реализация для таких случаев.

2020-05-13 09:23 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/OptimizedOptionSelector.java
> +                        cluster -> picker.getRepresentatives(cluster).get(0),
А зачем вы делали такой гибкий интерфейс, возвращающий List, если потом используете знание, что значение имеет ровно первый элемент? Может на самом деле вы хотели использовать Optional? Или я чего-то не понимаю?

2020-05-13 09:23 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/OptimizedOptionSelector.java
> +    public int getSelectionSize() { return 1; }
А почему тогда не от OptionSelector-а наследоваться? Зачем именно ManyOptionsSelector?

2020-05-13 09:23 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/FullDatasetEvaluation.java
> +//                }
Мммм, закомментированный код в пул-реквесте

2020-05-13 09:23 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/MarkingEvaluation.java
> +    }
Хороший метод

2020-05-13 09:23 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/ClustersCreator.java
> +//                        .sorted(Comparator.<Cluster<Solution>>comparingInt(Cluster::size).reversed())
Опять пустой метод с закомментированным кодом

2020-05-13 09:23 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/ClustersCreator.java
> +//                        .sorted(Comparator.<Cluster<Solution>>comparingInt(Cluster::size).reversed())
Тогда уж удалите его совсем

2020-05-13 09:23 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/ClustersCreator.java
> +    };
Если теперь мы работаем со всеми задачами, то что этот массив тут забыл?

2020-05-13 09:23 UTC, ArtyomLobanov commented on src/main/java/org/ml_methods_group/evaluation/preparation/ClustersCreator.java
> +                    BOWApproach.getDefaultApproach(20000, dataset, generator)));
Это полем тогда лучше сделать и принимать в конструкторе.

2020-05-21 10:08 UTC, SmirnovOleg commented on common/src/main/java/org/ml_methods_group/common/extractors/ManyProblemsBasedChangesExtractor.java
> +        return oracle.process(value);
Как её тут обработать? В try-catch завернуть только если? Просто это же проблема юзера, если он некорректную мапу дал, да и default значений тут нет, чтобы их использовать

2020-05-21 10:09 UTC, SmirnovOleg commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/OptimizedOptionSelector.java
> +                        cluster -> picker.getRepresentatives(cluster).get(0),
Просто в других случаях может потребоваться несколько центров, я пробовал с 3-мя, был примерно такой же перфоманс, и я удалил это позже

2020-05-21 10:12 UTC, SmirnovOleg commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/OptimizedOptionSelector.java
> +    public int getSelectionSize() { return 1; }
Тут глобальная проблема - я еще осенью переезжал на ManyOptionsSelector's везде где мог из-за аугментации по трем соседям, и стал в итоге все под них писать. Если использовать просто OptionSelector, то и генератор потом другой нужен, а значит и в создании датасетов нужно менять интерфейс у селектора. В общем, по идее это должен быть один интерфейс, но я не знаю, как их правильно смержить, из-за этого везде сейчас просто ManyOptionsSelectors использую (как более гибкий)

2020-05-21 10:14 UTC, SmirnovOleg commented on clustering/src/main/java/org/ml_methods_group/clustering/clusterers/HAC.java
> +    protected final Set<Community> communities = new HashSet<>();
Я временно выбрал 2ой вариант (как самый очевидный), на счет State - почему сейчас нельзя использовать параллельно для нескольких наборов данных? Это же не static поля, значит для каждого инстанса кластерера они свои будут, нет?

2020-05-28 06:52 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/extractors/ManyProblemsBasedChangesExtractor.java
> +        return oracle.process(value);
Можно бросить какую-нибудь понятную человекочитаемую ошибку UnexpectedProblemException вместо безликого NPE

2020-05-28 06:59 UTC, ArtyomLobanov commented on clustering/src/main/java/org/ml_methods_group/clustering/clusterers/HAC.java
> +    protected final Set<Community> communities = new HashSet<>();
Нельзя использовать одновременно один экземпляр. У класса есть внутреннее состояние, но только в момент вычисления кластеров и со стороны никак не проверить готов ли сейчас экземпляр к работе. Но пока и так норм.

2020-05-28 07:09 UTC, ArtyomLobanov commented on common/src/main/java/org/ml_methods_group/common/metrics/selectors/OptimizedOptionSelector.java
> +                        cluster -> picker.getRepresentatives(cluster).get(0),
Пока что нигде не утверждалось, что лучший элемент должен быть именно первым в списке. Можно унаследовать ManyOptionSelector от OptionSelectorи добавить в интерфейс дефолтный метод, который возвращает getRepresentatives(cluster).get(0). Таким образом мы передаём контроль над финальным выбором внутрь класса. Если класс знает, что нулевой элемент не лучший выбор, то он сможет переопределить этот метод.

2025-12-12 07:47 UTC, closed without merging

2025-12-12 07:47 UTC, stephanlukasczyk commented
Close PR to archive repository